"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Country = { id: string; name: string; assignmentId: string | null; email: string | null };
async function request(path: string, init: RequestInit = {}) { const { data: { session } } = await createClient().auth.getSession(); const r = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...init.headers, Authorization: `Bearer ${session?.access_token}` } }); const j = await r.json().catch(() => ({})); if (!r.ok) throw new Error(j.error?.message ?? "Request failed"); return j; }
export default function CountryAssignments() {
  const [countries, setCountries] = useState<Country[]>([]); const [countryId, setCountryId] = useState(""); const [email, setEmail] = useState(""); const [credential, setCredential] = useState<any>(); const [error, setError] = useState("");
  const load = () => request("/api/v1/countries").then(setCountries).catch((e) => setError(e.message)); useEffect(load, []);
  async function assign(e: React.FormEvent) { e.preventDefault(); setError(""); try { setCredential(await request("/api/v1/countries", { method: "POST", body: JSON.stringify({ countryId, email }) })); setEmail(""); setCountryId(""); load(); } catch (e) { setError((e as Error).message); } }
  async function updateCredential(country: Country, reassign = false) { const nextEmail = reassign ? window.prompt(`New email for ${country.name}:`, country.email ?? "") : undefined; if (reassign && !nextEmail) return; setError(""); try { setCredential(await request("/api/v1/countries", { method: "PATCH", body: JSON.stringify({ countryId: country.id, ...(nextEmail ? { email: nextEmail } : {}) }) })); load(); } catch (e) { setError((e as Error).message); } }
  function csv() { if (!credential) return; const line = `Country,Email,Password\n"${credential.country}","${credential.email}","${credential.password}"`; const url = URL.createObjectURL(new Blob([line], { type: "text/csv" })); const a = document.createElement("a"); a.href = url; a.download = "delegate-credentials.csv"; a.click(); URL.revokeObjectURL(url); }
  return <div className="p-6 sm:p-10 max-w-6xl mx-auto"><p className="text-xs uppercase tracking-[.18em] text-[#6CA9FF]">Executive board</p><h1 className="text-3xl font-semibold text-white mt-2">Country credentials</h1><p className="text-[#B6C3D1] mt-2">Assign one delegate account per immutable country entry.</p>{credential && <div className="mt-6 p-5 rounded-xl border border-amber-300/30 bg-amber-300/10"><p className="text-amber-100 font-medium">Save this credential now — it will not be shown again.</p><p className="text-white mt-2">{credential.country} · {credential.email} · <code>{credential.password}</code></p><button onClick={csv} className="mt-3 text-sm text-[#9AC5FF] underline">Download one-time CSV</button></div>}<form onSubmit={assign} className="mt-8 grid sm:grid-cols-[1fr_1fr_auto] gap-3"><select required value={countryId} onChange={(e) => setCountryId(e.target.value)} className="rounded-lg bg-[#0B2345] border border-white/10 px-3 py-2.5"><option value="">Select unassigned country</option>{countries.filter(c => !c.assignmentId).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="delegate@example.com" className="rounded-lg bg-[#0B2345] border border-white/10 px-3 py-2.5"/><button className="rounded-lg bg-[#2E78E9] px-4 py-2.5 font-medium">Generate login</button></form>{error && <p className="mt-3 text-red-300 text-sm">{error}</p>}<div className="mt-8 border border-white/10 rounded-xl overflow-hidden">{countries.map(c => <div key={c.id} className="p-4 flex flex-wrap items-center justify-between gap-4 border-b border-white/10 last:border-0"><span className="text-white">{c.name}</span><div className="flex items-center gap-3"><span className={c.email ? "text-[#B6C3D1]" : "text-[#7D8DA0]"}>{c.email ?? "Unassigned"}</span>{c.assignmentId && <><button onClick={() => updateCredential(c)} className="text-xs text-[#9AC5FF]">Reset password</button><button onClick={() => updateCredential(c, true)} className="text-xs text-[#9AC5FF]">Reassign</button></>}</div></div>)}</div></div>;
}
