"use client";
import { useEffect, useState, type FormEvent } from "react";
import { createClient } from "@/lib/supabase/client";

async function request(path: string, init: RequestInit = {}) { const { data: { session } } = await createClient().auth.getSession(); const r = await fetch(path, { ...init, headers: { ...init.headers, Authorization: `Bearer ${session?.access_token}` } }); const j = await r.json().catch(() => ({})); if (!r.ok) throw new Error(j.error?.message ?? "Request failed"); return j; }
type Party = { id: string; assignmentId: string; role: "complainant" | "respondent" | "third_party"; country: string; statement?: string | null; submittedAt?: string | null };
type ThirdPartyResponse = { assignmentId: string; country: string; response: "yes" | "no" };
type ReportFile = { id: string; fileName: string };
type FinalReport = { content?: string | null; externalUrl?: string | null; files: ReportFile[] };
type DisputeDetail = { disputeNumber: string; title: string; description: string; status: string; parties: Party[]; responses: ThirdPartyResponse[]; viewerThirdPartyResponse: "yes" | "no" | null; report: FinalReport | null };
const ROLE_LABELS: Record<Party["role"], string> = { complainant: "Complainants", respondent: "Respondents", third_party: "Approved third parties" };

function PartyStatements({ parties }: { parties: Party[] }) {
  const grouped = (["complainant", "respondent", "third_party"] as const).map((role) => [role, parties.filter((party) => party.role === role)] as const).filter(([, group]) => group.length);
  return <section className="mt-8"><div className="border-b border-white/10 pb-4"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#6CA9FF]">Parties & statements</p><h2 className="mt-2 text-xl font-semibold text-white">Live party record</h2><p className="mt-1 text-sm text-[#B6C3D1]">Approved third parties join this record when EB finalises participation.</p></div><div className="mt-5 grid gap-5 lg:grid-cols-3">{grouped.map(([role, group]) => <div key={role} className="rounded-xl border border-white/10 bg-[#071B35] p-4"><h3 className="text-sm font-semibold text-white">{ROLE_LABELS[role]} <span className="text-[#7D8DA0]">({group.length})</span></h3><div className="mt-3 space-y-3">{group.map((party) => <article key={party.id} className="rounded-lg border border-white/10 bg-[#05162D] p-3"><div className="flex items-center justify-between gap-3"><span className="font-medium text-white">{party.country}</span><span className={`rounded-full px-2 py-0.5 text-[11px] ${party.statement ? "bg-emerald-400/10 text-emerald-200" : "bg-amber-300/10 text-amber-100"}`}>{party.statement ? "Submitted" : "Pending"}</span></div>{party.statement ? <p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#B6C3D1]">{party.statement}</p> : <p className="mt-2 text-xs text-[#7D8DA0]">No statement submitted yet.</p>}</article>)}</div></div>)}</div></section>;
}

export default function DisputeDetailClient({ disputeId }: { disputeId: string }) {
  const [item, setItem] = useState<DisputeDetail>(); const [role, setRole] = useState("delegate"); const [error, setError] = useState(""); const [text, setText] = useState(""); const [chosen, setChosen] = useState<string[]>([]); const [reportText, setReportText] = useState(""); const [link, setLink] = useState(""); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false);
  const load = async () => { try { setItem(await request(`/api/v1/disputes/${disputeId}`) as DisputeDetail); } catch (e) { setError((e as Error).message); } };
  useEffect(() => { let active = true; void Promise.all([request("/api/v1/auth/session"), request(`/api/v1/disputes/${disputeId}`)]).then(([session, dispute]) => { if (!active) return; setRole(session.user?.role ?? "delegate"); setItem(dispute as DisputeDetail); }).catch((e: Error) => { if (active) setError(e.message); }); return () => { active = false; }; }, [disputeId]);
  async function action(path: string, body?: unknown) { setError(""); setBusy(true); try { await request(path, { method: "POST", headers: body ? { "Content-Type": "application/json" } : {}, body: body ? JSON.stringify(body) : undefined }); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function publish(e: FormEvent) { e.preventDefault(); setError(""); setBusy(true); try { const form = new FormData(); form.set("content", reportText); form.set("externalUrl", link); if (file) form.set("file", file); await request(`/api/v1/disputes/${disputeId}/final-report`, { method: "POST", body: form }); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (error && !item) return <div className="p-10 text-red-300">{error}</div>; if (!item) return <div className="p-10 text-[#B6C3D1]">Loading dispute…</div>;
  const yesResponses = item.responses.filter((response) => response.response === "yes"); const currentResponse = item.viewerThirdPartyResponse;
  return <div className="mx-auto max-w-6xl p-6 sm:p-10"><p className="text-xs uppercase tracking-[.18em] text-[#6CA9FF]">{item.disputeNumber}</p><div className="mt-2 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold text-white">{item.title}</h1><p className="mt-4 max-w-3xl whitespace-pre-wrap text-[#B6C3D1]">{item.description}</p></div><p className="rounded-full bg-[#0B315D] px-3 py-1 text-xs text-[#9AC5FF]">{item.status.replaceAll("_", " ")}</p></div>{error && <p className="mt-4 text-sm text-red-300" role="alert">{error}</p>}
    {role === "executive_board" && item.parties.length > 0 && <PartyStatements parties={item.parties} />}
    {role === "executive_board" && item.status === "pending_eb_review" && <section className="mt-8 flex gap-3"><button disabled={busy} onClick={() => void action(`/api/v1/disputes/${disputeId}/decision`, { decision: "approve" })} className="rounded-lg bg-emerald-600 px-4 py-2 text-white disabled:opacity-50">Approve</button><button disabled={busy} onClick={() => void action(`/api/v1/disputes/${disputeId}/decision`, { decision: "reject" })} className="rounded-lg bg-red-700 px-4 py-2 text-white disabled:opacity-50">Reject</button></section>}
    {role === "delegate" && item.status === "third_party_response" && <section className="mt-8 rounded-xl border border-white/10 bg-[#071B35] p-5"><h2 className="font-medium text-white">Third-party participation</h2><p className="mt-1 text-sm text-[#B6C3D1]">You can change your response until every eligible country has replied.</p><div className="mt-4 flex flex-wrap gap-3"><button disabled={busy} onClick={() => void action(`/api/v1/disputes/${disputeId}/third-party-response`, { response: "yes" })} className={`rounded-lg px-4 py-2 disabled:opacity-50 ${currentResponse === "yes" ? "bg-emerald-500 text-white ring-2 ring-emerald-200" : "bg-[#2E78E9] text-white"}`}>I want to be a third party{currentResponse === "yes" ? " · selected" : ""}</button><button disabled={busy} onClick={() => void action(`/api/v1/disputes/${disputeId}/third-party-response`, { response: "no" })} className={`rounded-lg px-4 py-2 disabled:opacity-50 ${currentResponse === "no" ? "bg-white/20 text-white ring-2 ring-white/40" : "bg-white/10 text-white"}`}>I do not want to participate{currentResponse === "no" ? " · selected" : ""}</button></div></section>}
    {role === "executive_board" && item.status === "third_party_eb_review" && <section className="mt-8 rounded-xl border border-white/10 bg-[#071B35] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-medium text-white">Third-party review</h2><p className="mt-1 text-sm text-[#B6C3D1]">Approve any subset of countries that opted in. Countries left unchecked will not join the proceeding.</p></div><div className="flex gap-3 text-xs"><button type="button" onClick={() => setChosen(yesResponses.map((response) => response.assignmentId))} className="text-[#9AC5FF] hover:text-white">Select all</button><button type="button" onClick={() => setChosen([])} className="text-[#9AC5FF] hover:text-white">Clear</button></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{yesResponses.map((response) => { const isChosen = chosen.includes(response.assignmentId); return <label key={response.assignmentId} className={`flex cursor-pointer items-center gap-3 rounded-lg border p-3 text-sm ${isChosen ? "border-[#2E78E9] bg-[#0B315D] text-white" : "border-white/10 bg-[#05162D] text-[#B6C3D1]"}`}><input type="checkbox" checked={isChosen} onChange={() => setChosen((current) => current.includes(response.assignmentId) ? current.filter((id) => id !== response.assignmentId) : [...current, response.assignmentId])} className="h-4 w-4 accent-[#2E78E9]" />{response.country}</label>; })}</div><button disabled={busy} onClick={() => void action(`/api/v1/disputes/${disputeId}/third-parties`, { approvedAssignmentIds: chosen })} className="mt-5 rounded-lg bg-[#2E78E9] px-4 py-2 text-white disabled:opacity-50">{busy ? "Finalising…" : `Finalise ${chosen.length} participant${chosen.length === 1 ? "" : "s"}`}</button></section>}
    {role === "delegate" && item.status === "statements_open" && item.parties.length > 0 && <section className="mt-8 rounded-xl border border-white/10 bg-[#071B35] p-5"><h2 className="font-medium text-white">Your {item.parties[0].role.replace("_", " ")} statement</h2>{item.parties[0].statement ? <p className="mt-3 text-[#B6C3D1]">Your final statement has been submitted and cannot be changed.</p> : <><p className="mt-1 text-sm text-amber-200">Submitting is final. You cannot edit this statement afterwards.</p><textarea value={text} onChange={(e) => setText(e.target.value)} rows={9} className="mt-4 w-full rounded-lg border border-white/10 bg-[#0B2345] p-3" /><button disabled={busy || !text.trim()} onClick={() => void action(`/api/v1/disputes/${disputeId}/statement`, { content: text })} className="mt-3 rounded-lg bg-[#2E78E9] px-4 py-2 text-white disabled:opacity-50">{busy ? "Submitting…" : "Submit final statement"}</button></>}</section>}
    {role === "executive_board" && item.status === "statements_open" && <button disabled={busy} onClick={() => void action(`/api/v1/disputes/${disputeId}/close-statements`)} className="mt-8 rounded-lg bg-[#2E78E9] px-4 py-2 text-white disabled:opacity-50">Close statement phase</button>}
    {role === "executive_board" && item.status === "statements_closed" && <form onSubmit={publish} className="mt-8 rounded-xl border border-white/10 bg-[#071B35] p-5"><h2 className="font-medium text-white">Publish final report</h2><textarea value={reportText} onChange={(e) => setReportText(e.target.value)} placeholder="Report text (optional)" rows={6} className="mt-4 w-full rounded-lg border border-white/10 bg-[#0B2345] p-3" /><input value={link} onChange={(e) => setLink(e.target.value)} placeholder="External link (optional)" className="mt-3 w-full rounded-lg border border-white/10 bg-[#0B2345] p-3" /><input type="file" accept="application/pdf,.docx" onChange={(e) => setFile(e.target.files?.[0] ?? null)} className="mt-3 text-sm" /><button disabled={busy} className="mt-4 rounded-lg bg-[#2E78E9] px-4 py-2 text-white disabled:opacity-50">{busy ? "Publishing…" : "Publish to all delegates"}</button></form>}
    {item.report && <section className="mt-8 rounded-xl border border-white/10 bg-[#071B35] p-5"><h2 className="font-medium text-white">Final report</h2>{item.report.content && <p className="mt-3 whitespace-pre-wrap text-[#B6C3D1]">{item.report.content}</p>}{item.report.externalUrl && <a href={item.report.externalUrl} target="_blank" rel="noreferrer" className="mt-3 block text-[#9AC5FF] underline">Open report link</a>}{item.report.files.map((fileItem) => <a key={fileItem.id} href={`/api/v1/reports/${fileItem.id}/download`} className="mt-3 block text-[#9AC5FF] underline">Download {fileItem.fileName}</a>)}</section>}</div>;
}
