"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
async function request(path: string, init: RequestInit = {}) { const { data: { session } } = await createClient().auth.getSession(); const r = await fetch(path, { ...init, headers: { ...init.headers, Authorization: `Bearer ${session?.access_token}` } }); const j = await r.json().catch(() => ({})); if (!r.ok) throw new Error(j.error?.message ?? "Request failed"); return j; }
type Party = { id: string; assignmentId: string; role: string; country: string; statement?: string | null };
export default function DisputeDetailClient({ disputeId }: { disputeId: string }) {
  const [item, setItem] = useState<any>(); const [role, setRole] = useState("delegate"); const [error, setError] = useState(""); const [text, setText] = useState(""); const [chosen, setChosen] = useState<string[]>([]); const [reportText, setReportText] = useState(""); const [link, setLink] = useState(""); const [file, setFile] = useState<File | null>(null);
  const load = () => request(`/api/v1/disputes/${disputeId}`).then(setItem).catch((e) => setError(e.message)); useEffect(() => { request("/api/v1/auth/session").then(x => setRole(x.user?.role ?? "delegate")); load(); }, [disputeId]);
  async function action(path: string, body?: unknown) { setError(""); try { await request(path, { method: "POST", headers: body ? { "Content-Type": "application/json" } : {}, body: body ? JSON.stringify(body) : undefined }); load(); } catch (e) { setError((e as Error).message); } }
  const dossier = useMemo(() => item?.parties?.reduce((out: Record<string, string>, party: Party) => { const label = party.role === "third_party" ? "Third parties" : `${party.role[0].toUpperCase()}${party.role.slice(1)}s`; out[label] = `${out[label] ?? ""}${party.country}\n${party.statement ?? "[No statement submitted]"}\n\n`; return out; }, {}) ?? {}, [item]);
  if (error && !item) return <div className="p-10 text-red-300">{error}</div>; if (!item) return <div className="p-10 text-[#B6C3D1]">Loading dispute…</div>;
  const yesResponses = item.responses?.filter((r: any) => r.response === "yes") ?? [];
  async function publish(e: React.FormEvent) { e.preventDefault(); setError(""); try { const form = new FormData(); form.set("content", reportText); form.set("externalUrl", link); if (file) form.set("file", file); await request(`/api/v1/disputes/${disputeId}/final-report`, { method: "POST", body: form }); load(); } catch (e) { setError((e as Error).message); } }
  return <div className="p-6 sm:p-10 max-w-5xl mx-auto"><p className="text-xs uppercase tracking-[.18em] text-[#6CA9FF]">{item.disputeNumber}</p><h1 className="text-3xl font-semibold text-white mt-2">{item.title}</h1><p className="text-[#B6C3D1] mt-4 whitespace-pre-wrap">{item.description}</p><p className="mt-5 inline-block px-3 py-1 text-xs rounded-full bg-[#0B315D] text-[#9AC5FF]">{item.status.replaceAll("_", " ")}</p>{error && <p className="mt-4 text-red-300 text-sm">{error}</p>}
    {role === "executive_board" && item.status === "pending_eb_review" && <section className="mt-8 flex gap-3"><button onClick={() => action(`/api/v1/disputes/${disputeId}/decision`, { decision: "approve" })} className="px-4 py-2 rounded-lg bg-emerald-600 text-white">Approve</button><button onClick={() => action(`/api/v1/disputes/${disputeId}/decision`, { decision: "reject" })} className="px-4 py-2 rounded-lg bg-red-700 text-white">Reject</button></section>}
    {role === "delegate" && item.status === "third_party_response" && <section className="mt-8 p-5 rounded-xl bg-[#071B35] border border-white/10"><h2 className="font-medium text-white">Third-party participation</h2><p className="text-sm text-[#B6C3D1] mt-1">Choose whether your country wishes to participate as a third party.</p><div className="mt-4 flex gap-3"><button onClick={() => action(`/api/v1/disputes/${disputeId}/third-party-response`, { response: "yes" })} className="px-4 py-2 bg-[#2E78E9] rounded-lg">I want to be a third party</button><button onClick={() => action(`/api/v1/disputes/${disputeId}/third-party-response`, { response: "no" })} className="px-4 py-2 bg-white/10 rounded-lg">I do not want to participate</button></div></section>}
    {role === "executive_board" && item.status === "third_party_eb_review" && <section className="mt-8 p-5 rounded-xl bg-[#071B35] border border-white/10"><h2 className="text-white font-medium">Third-party review</h2><p className="text-sm text-[#B6C3D1] mt-1">Approve the countries that opted in after all countries respond.</p><div className="mt-4 space-y-2">{yesResponses.map((r: any) => <label key={r.assignmentId} className="flex gap-2 text-white"><input type="checkbox" checked={chosen.includes(r.assignmentId)} onChange={() => setChosen(c => c.includes(r.assignmentId) ? c.filter(x => x !== r.assignmentId) : [...c, r.assignmentId])}/>{r.country}</label>)}</div><button onClick={() => action(`/api/v1/disputes/${disputeId}/third-parties`, { approvedAssignmentIds: chosen })} className="mt-5 px-4 py-2 rounded-lg bg-[#2E78E9]">Finalise participants</button></section>}
    {role === "delegate" && item.status === "statements_open" && item.parties.length > 0 && <section className="mt-8 p-5 rounded-xl bg-[#071B35] border border-white/10"><h2 className="text-white font-medium">Your {item.parties[0].role.replace("_", " ")} statement</h2>{item.parties[0].statement ? <p className="mt-3 text-[#B6C3D1]">Your final statement has been submitted and cannot be changed.</p> : <><p className="mt-1 text-sm text-amber-200">Submitting is final. You cannot edit this statement afterwards.</p><textarea value={text} onChange={(e) => setText(e.target.value)} rows={9} className="mt-4 w-full rounded-lg bg-[#0B2345] border border-white/10 p-3"/><button onClick={() => action(`/api/v1/disputes/${disputeId}/statement`, { content: text })} className="mt-3 px-4 py-2 rounded-lg bg-[#2E78E9]">Submit final statement</button></>}</section>}
    {role === "executive_board" && item.status === "statements_open" && <button onClick={() => action(`/api/v1/disputes/${disputeId}/close-statements`)} className="mt-8 px-4 py-2 rounded-lg bg-[#2E78E9]">Close statement phase</button>}
    {role === "executive_board" && ["statements_closed", "final_report_published"].includes(item.status) && <section className="mt-8 grid lg:grid-cols-2 gap-6"><div className="space-y-4">{Object.entries(dossier).map(([heading, value]) => <div key={heading} className="p-4 rounded-xl bg-[#071B35] border border-white/10"><div className="flex justify-between"><h2 className="text-white font-medium">{heading}</h2><button onClick={() => navigator.clipboard.writeText(value)} className="text-sm text-[#9AC5FF]">Copy</button></div><pre className="mt-3 whitespace-pre-wrap font-sans text-sm text-[#B6C3D1]">{value}</pre></div>)}</div>{item.status === "statements_closed" && <form onSubmit={publish} className="p-5 rounded-xl bg-[#071B35] border border-white/10 h-fit"><h2 className="text-white font-medium">Publish final report</h2><textarea value={reportText} onChange={e => setReportText(e.target.value)} placeholder="Report text (optional)" rows={6} className="mt-4 w-full rounded-lg bg-[#0B2345] border border-white/10 p-3"/><input value={link} onChange={e => setLink(e.target.value)} placeholder="External link (optional)" className="mt-3 w-full rounded-lg bg-[#0B2345] border border-white/10 p-3"/><input type="file" accept="application/pdf,.docx" onChange={e => setFile(e.target.files?.[0] ?? null)} className="mt-3 text-sm"/><button className="mt-4 px-4 py-2 rounded-lg bg-[#2E78E9]">Publish to all delegates</button></form>}</section>}
    {item.report && <section className="mt-8 p-5 rounded-xl bg-[#071B35] border border-white/10"><h2 className="text-white font-medium">Final report</h2>{item.report.content && <p className="mt-3 whitespace-pre-wrap text-[#B6C3D1]">{item.report.content}</p>}{item.report.externalUrl && <a href={item.report.externalUrl} target="_blank" className="block mt-3 text-[#9AC5FF] underline">Open report link</a>}{item.report.files.map((f: any) => <a key={f.id} href={`/api/v1/reports/${f.id}/download`} className="block mt-3 text-[#9AC5FF] underline">Download {f.fileName}</a>)}</section>}</div>;
}
