"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
type Country = { id: string; name: string; assignmentId: string | null; email: string | null };
async function request(path: string, init: RequestInit = {}) { const { data: { session } } = await createClient().auth.getSession(); const r = await fetch(path, { ...init, headers: { ...init.headers, Authorization: `Bearer ${session?.access_token}` } }); const j = await r.json().catch(() => ({})); if (!r.ok) throw new Error(j.error?.message ?? "Request failed"); return j; }
export default function DisputeForm() {
  const router = useRouter(); const [countries, setCountries] = useState<Country[]>([]); const [me, setMe] = useState<any>(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { request("/api/v1/countries").then(setCountries); request("/api/v1/users/me").then(setMe); }, []);
  const assigned = countries.filter((c) => c.assignmentId); const own = countries.find((c) => c.name === me?.country);
  async function submit(form: FormData) { setSaving(true); setError(""); try { const complainants = Array.from(form.getAll("complainants")).map(String); if (own?.assignmentId && !complainants.includes(own.assignmentId)) complainants.push(own.assignmentId); const dispute = await request("/api/v1/disputes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: form.get("title"), description: form.get("description"), complainantAssignmentIds: complainants, respondentAssignmentIds: Array.from(form.getAll("respondents")).map(String) }) }); router.push(`/disputes/${dispute.id}`); } catch (e) { setError((e as Error).message); } finally { setSaving(false); } }
  return <div className="p-6 sm:p-10 max-w-3xl mx-auto"><p className="text-xs uppercase tracking-[.18em] text-[#6CA9FF]">New filing</p><h1 className="text-3xl font-semibold text-white mt-2">Raise a dispute</h1><p className="text-[#B6C3D1] mt-2 mb-8">Your filing goes directly to the Executive Board for review.</p><form action={submit} className="space-y-6"><label className="block text-sm text-white">Title<input required name="title" maxLength={200} className="mt-2 w-full rounded-lg bg-[#0B2345] border border-white/10 px-3 py-2.5" /></label><label className="block text-sm text-white">Description<textarea required name="description" rows={7} className="mt-2 w-full rounded-lg bg-[#0B2345] border border-white/10 px-3 py-2.5" /></label><label className="block text-sm text-white">Complainant countries <span className="text-[#7D8DA0]">(your country is always included)</span><select name="complainants" multiple className="mt-2 w-full min-h-40 rounded-lg bg-[#0B2345] border border-white/10 px-3 py-2.5">{assigned.filter(c => c.assignmentId !== own?.assignmentId).map(c => <option key={c.id} value={c.assignmentId!}>{c.name}</option>)}</select></label><label className="block text-sm text-white">Respondent countries <span className="text-red-300">(required)</span><select required name="respondents" multiple className="mt-2 w-full min-h-40 rounded-lg bg-[#0B2345] border border-white/10 px-3 py-2.5">{assigned.filter(c => c.assignmentId !== own?.assignmentId).map(c => <option key={c.id} value={c.assignmentId!}>{c.name}</option>)}</select></label>{error && <p className="text-red-300 text-sm">{error}</p>}<button disabled={saving} className="px-5 py-2.5 rounded-lg bg-[#2E78E9] text-white font-medium disabled:opacity-50">{saving ? "Submitting…" : "Submit to Executive Board"}</button></form></div>;
}
